local options = {
  ensure_installed = {
    'ansible-language-server',
    'autoflake',
    'autopep8',
    'bash-language-server',
    'clang-format',
    'clangd',
    'cmake-language-server',
    'css-lsp',
    'debugpy',
    'deno',
    'docformatter',
    'docker-compose-language-service',
    'docker-lancuage-server',
    'eslint-lsp',
    'flake8',
    'grammarly-languageserver',
    'hadolint',
    'html-lsp',
    'lua-language-server',
    'prettier',
    'pyright',
    'python-lsp-server',
    'shellcheck',
    'stylua',
    'svelte-language-server',
    'tailwindcss-language-server',
    'terraform-ls',
    'typescript-language-server',
    'yaml-language-server',
    'yamlfmt',
  },

  ui = {
    keymaps = {
      toggle_server_expand = '<CR>',
      install_server = 'i',
      update_server = 'u',
      check_server_version = 'c',
      update_all_servers = 'U',
      check_outdated_servers = 'C',
      uninstall_server = 'X',
      cancel_installation = '<C-c>',
    },
  },

  max_concurrent_installers = 10,
}

return options
